-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.intervencion
(
    participant_num integer NOT NULL DEFAULT nextval('intervencion_participant_num_seq'::regclass),
    sustancias text[] COLLATE pg_catalog."default",
    intervencion text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.opciones
(
    id_opcion numeric NOT NULL,
    opciones text COLLATE pg_catalog."default",
    CONSTRAINT opciones_pkey PRIMARY KEY (id_opcion)
);

CREATE TABLE IF NOT EXISTS public.preguntas
(
    no_question numeric NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    CONSTRAINT preguntas_pkey PRIMARY KEY (no_question)
);

CREATE TABLE IF NOT EXISTS public.resultados
(
    participant_num integer NOT NULL DEFAULT nextval('resultados_participant_num_seq'::regclass),
    sustancias text[] COLLATE pg_catalog."default",
    puntuacion_por_sustancia numeric[],
    puntuacion_total numeric
);

CREATE TABLE IF NOT EXISTS public.riesgo
(
    participant_num integer NOT NULL DEFAULT nextval('riesgo_participant_num_seq'::regclass),
    sustancias text[] COLLATE pg_catalog."default",
    intervencion text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.sustancias
(
    id_sustancia integer NOT NULL,
    categoria text COLLATE pg_catalog."default",
    desc_categoria text COLLATE pg_catalog."default",
    CONSTRAINT sustancias_pkey PRIMARY KEY (id_sustancia)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    participant_num integer NOT NULL DEFAULT nextval('usuarios_participant_num_seq'::regclass),
    sexo text COLLATE pg_catalog."default",
    edad integer,
    ocupacion text COLLATE pg_catalog."default",
    clinica text COLLATE pg_catalog."default",
    barrio text COLLATE pg_catalog."default",
    estrato integer,
    CONSTRAINT usuarios_pkey PRIMARY KEY (participant_num)
);

ALTER TABLE IF EXISTS public.intervencion
    ADD CONSTRAINT intervencion_participant_num_fkey FOREIGN KEY (participant_num)
    REFERENCES public.usuarios (participant_num) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.resultados
    ADD CONSTRAINT resultados_participant_num_fkey FOREIGN KEY (participant_num)
    REFERENCES public.usuarios (participant_num) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.resultados
    ADD CONSTRAINT resultados_participant_num_fkey1 FOREIGN KEY (participant_num)
    REFERENCES public.usuarios (participant_num) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.riesgo
    ADD CONSTRAINT riesgo_participant_num_fkey FOREIGN KEY (participant_num)
    REFERENCES public.usuarios (participant_num) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;